### PR TITLE
JBIDE-19683 created doc-tutorial-data dir for tutorials data

### PR DESCRIPTION
**Pull request by jcmurphey**
PR for adding a tutorial tech doc data area to jbosstools download.

### CODE REVIEW

**Comment by maxandersen** [comment]
No, this looks wrong IMO. why not create these as quickstarts ?

**Comment by jcmurphey** [comment]
HI Max! These files are supplied for working through tutorials in the Fuse Tooling Tutorials guide. The tutorials are sequential, each one is based on the completion of the previous. These files enable experienced users to run through any of the tutorials in any order. I need a place to host these files, so that users can download them by clicking a hyperlink in the tutorials doc. I have a way to do this for the doc published to the Customer Portal using publican, but that method won't work for the online help doc built using Ant and supplied with the Fuse Tooling plugins.

**Comment by maxandersen** [comment]
what online help doc built using ant ? link please ? 

also, why not put these in a github repo and link to those and tell users to clone them ? 

I think its a bad idea to start pushing such data to jboss tools sites again - we did it in past, we don't want to repeat that if can be avoided.

**Comment by jcmurphey** [comment]
It's not yet built, but it will be. It's part of the JBoss Fuse Tooling plugins for JBDS. The user docs aren't ready yet for the 6.2 release in late June. I use Ant to build the help (online and context-sensitive). I can't use the Fuse Tooling repo because its currently on a development branch and will be moved to a release branch, which will break the hyperlinks in the doc.

**Comment by maxandersen** [comment]
can you please provide links to what you are trying to build ? you are asking for content to be put on jboss.org/tools but keep mentioning JBDS.

**Comment by maxandersen** [comment]
closing this since no additional feedback. Sad since sounded like we could have shared some of this functionality outside just Fuse.

**Pull request closed without merging**
